import AppDate from "./date";

const AppConstant = {
  login: {
    apiPath: "auth.php",
    storage: "USER-INFO",
    fields: {
      username: {
        name: "username",
        label: "Username",
        type: "text",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
      password: {
        name: "password",
        label: "Password",
        type: "password",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
    },
  },
  admin: {
    category: {
      apiPath: {
        read: "read.php",
        create: "category/create.php",
        update: "category/update.php",
        delete: "category/delete.php",
      },
      fields: {
        name: {
          name: "name",
          label: "Category Name",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: false,
          value: "",
        },
        detail: {
          name: "detail",
          label: "Category Detail",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: true,
          rows: 4,
          value: "",
        },
      },
    },
    subCategory: {
      apiPath: {
        create: "sub_category/create.php",
        update: "sub_category/update.php",
        delete: "sub_category/delete.php",
      },
      fields: {
        name: {
          name: "name",
          label: "Sub Category Name",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: false,
          value: "",
        },
        detail: {
          name: "detail",
          label: "Sub Category Detail",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: true,
          rows: 4,
          value: "",
        },
      },
    },
  },
  expense: {
    apiPath: {
      read: "read.php",
      create: "exp_data/create.php",
      update: "exp_data/update.php",
      delete: "exp_data/delete.php",
    },
    storage: "EXPENSE-INFO",
    fields: {
      date: {
        name: "date",
        label: "Category date",
        type: "date",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: new Date(),
      },
      category: {
        name: "category",
        label: "Expense Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      detail: {
        name: "detail",
        label: "Expense Sub Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      amount: {
        name: "amount",
        label: "Expense Amount",
        type: "number",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
      note: {
        name: "note",
        label: "Expense Detail",
        type: "text",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: true,
        rows: 3,
        value: "",
      },
    },
    listFields: {
      date: {
        name: "date",
        label: "Select date",
        type: "date",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        minDate: false,
      },
      user: {
        name: "user",
        label: "Select User",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      isPaid: {
        name: "isPaid",
        label: "Select Paid/Not Paid",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [
          { id: true, name: "Paid" },
          { id: false, name: "Not Paid" },
        ],
      },
      category: {
        name: "category",
        label: "Expense Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      detail: {
        name: "detail",
        label: "Expense Sub Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
    },
  },
  report: {
    apiPath: {
      read: "read.php",
      create: "exp_data/create.php",
      update: "exp_data/update.php",
      delete: "exp_data/delete.php",
    },
    storage: "EXPENSE-INFO",
    fields: {
      startDate: {
        name: "startDate",
        label: "Start date",
        type: "startDate",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: AppDate.getDateIntoString(),
      },
      endDate: {
        name: "endDate",
        label: "End date",
        type: "endDate",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: AppDate.getDateIntoString(),
      },
      category: {
        name: "category",
        label: "Expense Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      detail: {
        name: "detail",
        label: "Expense Sub Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      amount: {
        name: "amount",
        label: "Expense Amount",
        type: "number",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
    },
  },
};
export default AppConstant;
